PROG=		main
SRCS=		main.c \
		../../coordinate.c \
		../../dijkstra.c \
		../../err.c \
		../../level.c \
		../../ui.c \

CSTD?=		c11
WARNS?=		6

LDADD=		-lncurses

MK_MAN=		no

.include <bsd.prog.mk>
